// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig/AppConfig.vue')['default']
    BubblyBg: typeof import('./src/components/CSSEffect/BubblyBg/index.vue')['default']
    ConfigItem: typeof import('./src/components/AppConfig/ConfigItem.vue')['default']
    DragHandle: typeof import('./src/components/AppConfig/DragHandle.vue')['default']
    FluidSimulation: typeof import('./src/components/CSSEffect/FluidSimulation/index.vue')['default']
    Galaxy: typeof import('./src/components/CSSEffect/Galaxy/index.vue')['default']
    LanguageSelector: typeof import('./src/components/AppConfig/LanguageSelector.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NeonHexagon: typeof import('./src/components/CSSEffect/NeonHexagon/index.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    OrbitalTrails: typeof import('./src/components/CSSEffect/OrbitalTrails/index.vue')['default']
    Particles: typeof import('./src/components/CSSEffect/Particles/index.vue')['default']
    PrimaryColorSelector: typeof import('./src/components/AppConfig/PrimaryColorSelector.vue')['default']
    Product: typeof import('./src/components/AppConfig/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplexNoiseParticles: typeof import('./src/components/CSSEffect/SimplexNoiseParticles/index.vue')['default']
    ThemeSelector: typeof import('./src/components/AppConfig/ThemeSelector.vue')['default']
    Waves: typeof import('./src/components/CSSEffect/Waves/index.vue')['default']
  }
}
